### ISSUE TITLE
BUG: Cannot set minimum and maximum bounds on windows width and height on macOS

### ISSUE THREAD

**Issue by thewebdev** [webview/webview_c#5]
**Platform**
macOS Mojave 10.14.6, Apple clang version 11.0.0 (clang-1100.0.33.17), Target: x86_64-apple-darwin18.7.0

**Expected**
Be able to set the minimum and and maximum window size using `WEBVIEW_HINT_MIN` and `WEBVIEW_HINT_MAX` 

**Issue**
No window is displayed at all when `WEBVIEW_HINT_MIN` and `WEBVIEW_HINT_MAX` is passed to `webview_set_size`

**Notes**
1. No errors on compilation. 
2. WEBVIEW_HINT_NONE and WEBVIEW_HINT_FIXED work as defined.

**Comment by petabyt** [comment]
Can you move these issues to https://github.com/webview/webview/issues? This is just an example repository.

**Comment by thewebdev** [comment]
Ok, will do. I posted here because I wasn't sure whether the issue is with the example C program or the library.

**Comment by thewebdev** [comment]
Moved to [webview  #723](https://github.com/webview/webview/issues/723)
